### PR TITLE
First pass on implementing PSR logger interface

### LINKED ISSUE #520: Custom Logging
It's pretty common to send log messages to a database or service, instead of logging to a file.  It seems odd that the SDK only allows logging to a file (or syslog, apparently).  Any thoughts on enabling the ability to add a custom log handler?  I imagine this could look like a simple callback function, set in the config, or the option to pass a custom `PayPalLoggingManager ` instance.

### PR DESCRIPTION
**Pull request by jaypatel512**
### Purpose
The purpose of this PR is to enable ability to plug in loggers implementing [PSR Logging Interface](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md).

- Created a separate PayPalLogger as default implementation.
- Enabled `log.Adapter` as a configuration to pass name of custom
  logger.
- Fixes #520 and #491 

### Steps to Implement custom logger

- Create a class implementing [PayPalLogFactory](https://github.com/paypal/PayPal-PHP-SDK/blob/logger-interface/lib/PayPal/Log/PayPalLogFactory.php). Look at [PayPalDefaultLogFactory](https://github.com/paypal/PayPal-PHP-SDK/blob/logger-interface/lib/PayPal/Log/PayPalDefaultLogFactory.php) for reference. Here is an example CustomLogFactory using Monolog Logger:
    ```php
<?php
use PayPal\Log\PayPalLogFactory;
use Psr\Log\LoggerInterface;

class MonologLogFactory implements PayPalLogFactory
{

    /**
     * Returns logger instance implementing LoggerInterface.
     *
     * @param string $className
     * @return LoggerInterface instance of logger object implementing LoggerInterface
     */
    public function getLogger($className)
    {
        $logger = new Monolog\Logger($className);
        $logger->pushHandler(new Monolog\Handler\StreamHandler("mail.log"));

        return $logger;
    }
}
```

- Set `log.AdapterFactory` settings in your `$apiContext->setConfig()` method as shown below:
    ```php
$apiContext->setConfig(
        array(
            ...
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'DEBUG',
            'log.AdapterFactory' => 'MonologLogFactory' // Factory class implementing \PayPal\Log\PayPalLogFactory
            ...
        )
    );
```
- Thats it. Run some code, and see the `mail.log` file getting created and logged with debug messages.
- NOTE: be sure to add `monolog\monolog` as a dependency in composer for this example.

### Checklist

- [x] Create dependency on PSR/Log.
- [x] Create default PayPalLogger to support default operations.
- [x] Enable configuration to set custom logging implementation.
- [x] Provide [PayPalLogFactory](https://github.com/paypal/PayPal-PHP-SDK/blob/logger-interface/lib/PayPal/Log/PayPalLogFactory.php) interface to be implemented by developers.
- [x] Provide [PayPalDefaultLogFactory](https://github.com/paypal/PayPal-PHP-SDK/blob/logger-interface/lib/PayPal/Log/PayPalDefaultLogFactory.php) to use default [PayPalLogger](https://github.com/paypal/PayPal-PHP-SDK/blob/logger-interface/lib/PayPal/Log/PayPalLogger.php) if no configuration provided.
- [x] Provide ability to inject factory implementation.
- [x] Update LoggingManager to work properly.
- [x] Testing
- [ ] Documentation Updates
- [x] Code Cleanup

### CODE REVIEW

**Comment by dopesong** [comment]
It should not only create new instance for logger. For example I have my logger inside my DI Container and I should be able to pass already created instance. :)

**Comment by jaypatel512** [comment]
Agreed @dopesong ! 

I have updated the code accordingly. Feel free to revisit, and test it out. I have added documentation in PR to create and configure your own logger.

**Comment by dopesong** [comment]
I not really understand why you have to create some factory class or something like this?
Config should just simply accept Class which implements `Psr\Log\LoggerInterface`

So in my case it would be something like this:

```php
'log.Logger' => $container['logger'] //Implements Psr\Log\LoggerInterface
```

and that's it. :)

Also you can check if `string` is provided to log.Logger - in that case check class_exists and instance of.
Both yes - create new instance of logger :)

**Comment by jaypatel512** [comment]
This does not allow you to provide the logger using configuration file. Our SDK has the ability to take sdk_config.ini files as configurations instead of passing the apiContext. 

To provide both scenarios, we need to get the logger factory class to allow you to create a new logger instance for us. You could simply pass the `$container['logger']` there too.

**Comment by dopesong** [comment]
I not really understand why you merged this before any agreement of community. You should not be the only one who decides. It's great that you develop this lib, but seriously what's the point of lib which is build by one guy. 

You should consider of best practices of PHP. In this case there is useless factory class which is used.

As one of great company you should provide the correct implementations ant solutions - but right now you releasing things which are unthinkable.

**Comment by jaypatel512** [comment]
Hey @dopesong !

I understand your concerns. We did talk about the decisions made to implement the way we are allowing the injection. To support the configuration file based injection, we do not find any middle ground where we could make it easier than this.

We do want to keep this SDK open source, and welcome any improvements from the community. Please feel free to create a new Pull Request with a better solution, and we would be more than happy to evaluate and merge that into our code. 

Let me know if you need any help setting up the developer environment to submit the pull request.

**Pull request merged**
