### PR TITLE
Adding transaction fee support to Capture class

### PR DESCRIPTION
**Pull request by wangjohnnywang**
The newest version is missing capture:: get/set transactionFee. Response we getting assumes the setTransactionFee exists:

Error: 
PayPal\Validation\ModelAccessorValidator: WARNING	: Missing Accessor: PayPal\Api\Capture:setTransactionFee. Please let us know by creating an issue at https://github.com/paypal/PayPal-PHP-SDK/issues

JSON response: 
 "capture":{
                  "id":"9N8867483A7827725",
                  "create_time":"2015-02-27T03:19:45Z",
                  "update_time":"2015-02-27T03:19:46Z",
                  "amount":{
                     "total":"24.04",
                     "currency":"USD"
                  },
                  "state":"completed",
                  "parent_payment":"PAY-4RB13686U5566814TKTX6DUA",
                  "transaction_fee":{
                     "value":"1.00",
                     "currency":"USD"
                  },
                  "links":[
                     {
                        "href":"https://api.sandbox.paypal.com/v1/payments/capture/9N8867483A7827725",
                        "rel":"self",
                        "method":"GET"
                     },
                     {
                        "href":"https://api.sandbox.paypal.com/v1/payments/capture/9N8867483A7827725/refund",
                        "rel":"refund",
                        "method":"POST"
                     },
                     {
                        "href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-4RB13686U5566814TKTX6DUA",
                        "rel":"parent_payment",
                        "method":"GET"
                     }
                  ]
               }

### CODE REVIEW

**Comment by jaypatel512** [comment]
Hey @wangjohnnywang ! Thank you so much for a quick pull request. I am also working on making all the updates to newer Payment API fields, and add the getter setter for them. I am almost done, and should be able to make a release soon. 

Thank you so much for your pull request.

**Comment by justiniso** [comment]
@jaypatel512 you deserve a gold star for your responsiveness to the community here. Really, thank you! It's been 11 hours and counting since we last heard from Paypal's merchant technical support (with many emails from us in between). And their last message to us tried to convince us that it was a problem with our code. Without you, we would be completely in the dark about this (and losing sales all the while!). Looking forward to the update that includes the getters/setters. Thanks again for your help.

**Comment by jziaja** [comment]
Totally agree with you @justiniso :+1: :)

**Comment by jaypatel512** [comment]
Thanks @justiniso for your kind words. I think my deeper knowledge on the PHP SDK allows me to be quick on helping with issues. 

Btw, once you update to the latest version of PHP SDK, you should be able to receive payments as before. Even though you are seeing warning in logs saying "WARNING: Missing Accessor .... ", the SDK should work fine. Only the new fields that are introduced in the Payment APIs are missing their getter setters. We included this feature to let external developer know that there are new fields that are present, that they could use, by updating to latest version. 

Once I have newer Payment API updates in our SDK in place, you should again be able to just click on update, and you will get all these new fields in the SDK. I feel bad that I couldnt figure the bug out before, and led to so many people rushing to update it. however, I am trying my best to resolve issues as much as I could.

**Comment by justiniso** [comment]
So we started integrating with v1.2.1 but we face a couple of challenges with it. For starters, we are upgrading from a pre-1.0 version (0.13.0) and are auditing our code for anything impacted by: https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0

Separately, we do captures in a try-catch. Which we've come to rely on to know whether charging the customer failed (e.g. if PayPal has unplanned downtime, insufficient funds, etc.). If it fails, we cancel the order. So while the capture is succeeding, the error is still causing us to cancel orders, resulting in a weird state where we've taken money but won't fulfill the customer's order (yikes). We're exploring handling that differently, but would prefer a stable version to work with so we can focus on the first issue (fixing 1.0 breaking changes). I know this is a loaded question--because I get it all the time, but do you have an idea of approximate timeframe for next release to get rid of the warning?

**Comment by jaypatel512** [comment]
It should be as soon as possible. I already have the models updated. I am just starting to complete functional tests. The Payment API new release is the highest priority.

**Comment by justiniso** [comment]
Great! I'm headed to bed for tonight, but let us know if there is anything you need from us (logs, code, repro, etc.) and we can look into getting it for you in the morning. We'll also be sure to try out the new version as soon as possible and see if we can break it ;)

**Comment by jaypatel512** [comment]
Hey @wangjohnnywang ! I am closing this PR without accepting it, as the sdk generator has already created that for me, and I was already half way through. however, I am very glad you sent us a PR. Please do not hesitate to do so in future.

@justiniso  In the mean time, to update everyone, I have created a new branch `Payment-API` that includes the changes to Payment API Models. I still have to add more functional tests to this. However, in the mean time, you could possibly test it out on your local machine by using `dev-Payment-API` as your version in composer file. I will complete all functional test and then merge it to master, and make a release soon.

**Comment by wangjohnnywang** [comment]
great, thanks @jaypatel512

**Comment by kulrisa** [comment]
W

**Pull request closed without merging**
