### PR TITLE
Fix for ValidateWebhookEvent - Fatal error

### PR DESCRIPTION
**Pull request by prakash-gangadharan**
**Fix for the issue #1141**
Added recent valid webhook event to the sample program.
PayPal-PHP-SDK/sample/notifications/ValidateWebhookEvent.php

### CODE REVIEW

**Comment by jagadeeshdeepak** [comment]
@prakash-gangadharan what does this PR exactly do? 
Is it to validate a sample webhook payload?

**Comment by prakash-gangadharan** [comment]
@jagadeeshdeepak, 
This is the example https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/notifications/ValidateWebhookEvent.php
to validate the webhook directly, from the received data. Which was not working now, hence updated the same with the recent webhook sample.

**Comment by jagadeeshdeepak** [comment]
@prakash-gangadharan got it. Changes look good to me. Please squash the commits into one and then merge. thanks!

**Comment by prakash-gangadharan** [comment]
@jagadeeshdeepak, thank you!

**Pull request merged**
