### PR TITLE
Test against php 7.3

### PR DESCRIPTION
**Pull request by BackEndTea**

### CODE REVIEW

**Comment by prakash-gangadharan** [comment]
Hi @BackEndTea,  does adding the php version 7.3 in travis.yml , will run the tests in that specific version?

**Comment by BackEndTea** [comment]
Yes the test now also run on php 7.3

**Comment by prakash-gangadharan** [comment]
https://github.com/paypal/PayPal-PHP-SDK/pull/1300/commits/a723222f1b4df5a3de9869157971c768e96a4742

**Comment by BackEndTea** [comment]
Cheers

**Comment by prakash-gangadharan** [comment]
@BackEndTea, thank you for the PR

**Pull request closed without merging**
