### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by avidas**
Do not generate docs for pull request. Update favicon link and update documentation for sdk documentation generation.

### CODE REVIEW

**Comment by jaypatel512** [comment]
Hey, would it make sense if we make check for master branch too ? Probably `TRAVIS_BRANCH` for this.

**Comment by avidas** [comment]
Makes sense to me, you still need to check for TRAVIS_PULL_REQUEST as TRAVIS_BRANCH is set to master for pull requests against master.

**Comment by jaypatel512** [comment]
Aah !! Didnt knew that. Makes sense. If we keep both TRAVIS_PULL_REQUEST and TRAVIS_BRANCH, we would get more specific runs.

**Comment by avidas** [comment]
Yeah, master as current source of truth for both codebase and documentation

**Pull request merged**
