### PR TITLE
Fix links to Developer API Reference

### PR DESCRIPTION
**Pull request by prakash-gangadharan**
Fix for Developer API Reference links not redirecting to the intended page #1301
**Description:**
links to Developer API Reference in the samples is not working and it always redirecting to REST APIs Get Started Page

### CODE REVIEW

**Comment by prakash-gangadharan** [comment]
Webhook samples has been updated with the below existing doc link.

| Previous link        | Existing Doc link           |
| ------------- |-------------| 
|https://developer.paypal.com/docs/api/#create-a-webhook	|	https://developer.paypal.com/docs/api/webhooks/v1/#webhooks_post |
|https://developer.paypal.com/docs/api/#list-all-webhooks	|	https://developer.paypal.com/docs/api/webhooks/v1/#webhooks_list |
|https://developer.paypal.com/docs/api/#delete-a-webhook	|	https://developer.paypal.com/docs/api/webhooks/v1/#webhooks_delete |
|https://developer.paypal.com/docs/api/#update-a-webhook	|	https://developer.paypal.com/docs/api/webhooks/v1/#webhooks_update |
|https://developer.paypal.com/docs/api/#get-a-webhook	|	https://developer.paypal.com/docs/api/webhooks/v1/#webhooks_get |
|https://developer.paypal.com/docs/api/webhooks/#verify-webhook-signature_post | https://developer.paypal.com/docs/api/webhooks/v1/#verify-webhook-signature |
|https://developer.paypal.com/docs/api/#search-webhook-events	|	https://developer.paypal.com/docs/api/webhooks/v1/#webhooks-events_list |
|https://developer.paypal.com/docs/api/#get-a-reference-list-of-webhook-event-types		|https://developer.paypal.com/docs/api/webhooks/v1/#webhooks-event-types_list |

**Comment by prakash-gangadharan** [comment]
Billing samples has been updated with the below existing doc link.

| Previous link        | Existing Doc link           |
| ------------------- |---------------------|
|https://developer.paypal.com/docs/api/#create-an-agreement   	|	https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_post|
|https://developer.paypal.com/docs/api/#create-a-plan	|	https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_post|
|https://developer.paypal.com/docs/api/#retrieve-an-agreement	|	https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_get|
|https://developer.paypal.com/docs/api/#retrieve-a-plan	|	https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_get|
|https://developer.paypal.com/docs/api/#list-plans	|	https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_list|
|https://developer.paypal.com/docs/api/#suspend-an-agreement		|https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_suspend|
|https://developer.paypal.com/docs/api/#search-for-transactions		|https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_transactions|
|https://developer.paypal.com/docs/api/#update-an-agreement		|https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_patch|
|https://developer.paypal.com/docs/api/#update-a-plan	|	https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_patch|

**Comment by jagadeeshdeepak** [comment]
Looks good to me.
[General] Squash the commit to one before merging.

**Comment by prakash-gangadharan** [comment]
@jagadeeshdeepak sure and Thanks!

**Pull request merged**
