### PR TITLE
Update CreatePlan.php

### PR DESCRIPTION
**Pull request by MartyIX**

### CODE REVIEW

**Comment by jziaja** [comment]
The `frequency` property is case-insensitive and will accept either "Month" or "MONTH".  Also, if you pass in "MONTH", you'll currently get back "Month" from the API.

**Comment by MartyIX** [comment]
PaymentDefinition.php file contains the following phpdoc:

    /**
     * Frequency of the payment definition offered. Allowed values: `WEEK`, `DAY`, `YEAR`, `MONTH`.
     *
     * @param string $frequency
     * 
     * @return $this
     */
    public function setFrequency($frequency)
    {
        $this->frequency = $frequency;
        return $this;
    }

It seems to me that the naming should follow one convention. However, it is just a suggestion. I can close the pull request. It is not something important to me.

**Comment by jziaja** [comment]
Sorry, wasn't trying to say it was a bad suggestion. :)  I prefer the consistency of having it be all caps, but I just wanted to point out that that field happens to accept any case format when making the API call.  In the [.NET SDK sample for creating a billing plan](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/BillingPlanCreate.aspx.cs#L75), I have this field specified as all caps as well.

**Comment by MartyIX** [comment]
I see. Thank you for the explanation.

**Comment by jaypatel512** [comment]
Hey @MartyIX !! I will unfortunately not accept this PR. Even though you are right. These constants should be CAPITALIZED ! :P 

However, the response from server is Camel Cased, and we would want to keep it that way. But I will definitely raise this issue internally, to see if we could have all CAPS accepted in Server Side code.

Thanks.

**Pull request closed without merging**
