### PR TITLE
Added condition to ignore extra header

### PR DESCRIPTION
**Pull request by gaurangrajvir**
I have added condition to ignore extra header which dont have colon ( : ) 
I am currently facing issue in my project and I am taking paypal sdk from composer..

is it the right source to update or any other ?

### CODE REVIEW

**Comment by gaurangrajvir** [comment]
Can you please check this request asap ? 

Its blocker for my project.

**Comment by gaurangrajvir** [comment]
also created issue > https://github.com/paypal/PayPal-PHP-SDK/issues/1059

**Comment by jaypatel512** [comment]
Hey @gaurangrajvir ! 

Do you have the sample response data that you get back from proxy ? this should help us add a test to make sure we handle this correctly.

**Comment by gaurangrajvir** [comment]
Hello @jaypatel512 

Here is the sample response ( in bold )  header with the use of Proxy ..

/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string **'HTTP/1.0 200 Connection established**
' (length=37)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string **'
'** (length=2)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**HTTP/1.1 200 OK**
' (length=17)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string **'Date: Thu, 15 Feb 2018 04:00:41 GMT**
' (length=37)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string **'Server: Apache**
' (length=16)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**paypal-debug-id: 6e83cb31413d7**
' (length=32)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string 'X-**PAYPAL-TOKEN-SERVICE: IAAS**
' (length=30)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**HTTP_X_PP_AZ_LOCATOR: sandbox.slc**
' (length=35)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**Paypal-Debug-Id: 6e83cb31413d7**
' (length=32)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3909453146%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Thu, 15 Feb 2018 04:30:41 GMT; domain=.paypal.com; path=/; Secure; HttpOnly**
' (length=241)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string **'Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT**
' (length=66)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**Vary: Authorization**
' (length=21)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**Content-Length: 550**
' (length=21)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string **'Connection: close**
' (length=19)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '**Content-Type: application/json**
' (length=32)
/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:76:string '
' (length=2)

If we call without proxy then , first two line of header response is not there so it is working fine. but issue when we call with the use of proxy.

Please let me know if you need more details.

thanks,
Gaurang

**Comment by gaurangrajvir** [comment]
Can you please check this ?

**Comment by gaurangrajvir** [comment]
Hello,
Can you please check this and do needful ?

Thanks,
Gaurang

**Comment by gaurangrajvir** [comment]
any update on this ?

**Comment by bluk** [comment]
Thanks for the PR. Will add this to the next release.

**Comment by gaurangrajvir** [comment]
Thanks

**Comment by gaurangrajvir** [comment]
Can you please create a new Tag and release it ?

**Comment by jansabat** [comment]
Hi, I have the same problem when connecting via proxy.

**Pull request merged**
