### PR TITLE
Remove credit card samples

### PR DESCRIPTION
**Pull request by pp-randy**
Remove credit card samples

### CODE REVIEW

**Comment by pp-randy** [comment]
Needs to be squash merged

**Comment by rogerrogers** [comment]
This is a really confusing commit. Does this mean PayPal are no longer supporting direct credit card purchases and billing agreements? To remove these samples from the SDK seems to indicate a hard deprecation for these features in favor of BrainTree. Is that correct? Having built projects using these features, but with the PayPal REST API, assuming that it was going to be supported, this is quite disturbing. A clear roadmap on this would be helpful. Are Billing Plans and Agreements using credit card still supported? Is removing these samples just a way of strongly suggesting the use of BrainTree or a definite deprecation of these features?

**Comment by xiaoleih41** [comment]
It is a definite deprecation for REST API integration. The credit card related API reference has been removed from developer.paypal.com as well. Braintree supports not only credit card, PayPal payment methods but also other popular methods as well. Braintree credit card integration is the direction that PayPal is taking going forward.

**Comment by rogerrogers** [comment]
Does this explain the 500 server errors I'm getting when trying to create a new Card Billing Agreement? Has PayPal released a roadmap for these features?

**Comment by xiaoleih41** [comment]
@rogerrogers You might have used an overused sandbox credit card number. If you try a newly randomly generated card number, it may work fine. Braintree as a recurring payment feature that has a lot of great feature. You can add PayPal as a payment method as well. Going forward, REST API will only handle products funded by PayPal only.

**Pull request merged**
